### ISSUE TITLE
请问关于MUI如何使用

### ISSUE THREAD

**Issue by xlgosin** [rockuw/oss-in-browser#1]
请问，我使用了MUI框架（一个H5框架），本身不兼容ES6语法，我应该如何使用客户端直接上传到oss呢。谢谢。

**Comment by rockuw** [comment]
MUI我不太了解，你可以贴一段要使用oss client的代码出来吗？

**Comment by xlgosin** [comment]
我使用的是oss-in-browser的代码，在chrome上面是可以上传成功的。
MUI主要应该是不兼容ES6的语法 例如yield、function*之类的。

**Comment by rockuw** [comment]
你参考这个用`babel`转换一下就可以了：https://github.com/rockuw/oss-in-browser#develop

**Comment by rockuw** [comment]
@xlgosin 使用OSS JavaScript SDK 4.3.0以上版本可以使用callback的方式，不需要`co`了：

https://github.com/ali-sdk/ali-oss#wrapper-usage

**Comment by xlgosin** [comment]
谢谢哈！这个应该可以试试，我后面用上传自己服务器，再服务器提交oss解决了。

**Comment by rockuw** [comment]
你这样当规模大起来的时候你的服务器会成为瓶颈的哦

**Comment by xlgosin** [comment]
一些后台的操作而已，目前没关系的。麻烦了哈。
