### ISSUE TITLE
上传时会跳转链接为"...?partNumber=1&uploadId=..."

### ISSUE THREAD

**Issue by zhuyuanwen** [rockuw/oss-in-browser#10]
![image](https://user-images.githubusercontent.com/12319327/30591285-bc5abb28-9d74-11e7-83df-c0b973be3142.png)
@rockuw 我昨天在一台mac上面上传成功了，成功时跳转的链接是"...?max-keys=100"。
今天换了一台mac测试，就失败了，跳转了好几个地址，如截图。然后最后一个失败了，400，打开提示的错误信息是：
`<Error>
<Code>AccessDenied</Code>
<Message>Anonymous user has no right to access this object.</Message>
<RequestId>59C10452ED0B5923D97CD756</RequestId>
<HostId>code-deepano.oss-cn-shanghai.aliyuncs.com</HostId>
</Error>`

那几个跳转的奇怪的链接，前面几个都是200，最后一个400，错误信息是：
`<Error>
<Code>InvalidPart</Code>
<Message>One or more of the specified parts could not be found or the specified entity tag might not have matched the part's entity tag.</Message>
<RequestId>59C08EAA6816B70219427E18</RequestId>
<HostId>code-deepano.oss-cn-shanghai.aliyuncs.com</HostId>
<ETag>undefined</ETag>
<PartNumber>1</PartNumber>
<UploadId>E15687AE7D7D45DE92F9A1503F557B9A</UploadId>
</Error>`

**Comment by zhuyuanwen** [comment]
然后，我又测试了一个android也是同样的情况。

**Comment by rockuw** [comment]
设置bucket属性

> expose 'ETag' in expose headers
