### ISSUE TITLE
使用multipartUpload上传超过100kb文件出错

### ISSUE THREAD

**Issue by we125182** [rockuw/oss-in-browser#11]
使用multipartUpload上传超过100kb文件时， 使用了分片上传， 导致报错
![2017-09-29_172630](https://user-images.githubusercontent.com/17947588/31010005-ee780b64-a53b-11e7-98ec-956b1858f402.png)

能给出前端multipartUpload分片上传大文件的实例吗？希望得到任何相关的建议， 谢谢！

**Comment by MissCuriosity** [comment]
这个问题我也遇到了，请问你解决了吗？

**Comment by rockuw** [comment]
设置bucket属性

> expose 'ETag' in expose headers
