### ISSUE TITLE
IE10下报 对象不支持“fill”属性或方法 的错误

### ISSUE THREAD

**Issue by gaochongid** [rockuw/oss-in-browser#3]
系统：MAC WIN8 虚拟机 IE模式IE10
SDK版本：Aliyun OSS SDK for JavaScript v4.4.3

![066d612e-978c-4ffe-932b-4c172f79fb83](https://cloud.githubusercontent.com/assets/4160727/15644032/1b9fb2d8-2683-11e6-88ff-ec209a5c63b9.png)

**Comment by rockuw** [comment]
谢谢反馈，我先看一下。

**Comment by rockuw** [comment]
原因已经找到，见 https://github.com/ali-sdk/ali-oss/pull/118

**Comment by gaochongid** [comment]
看到了，谢谢。

**Comment by rockuw** [comment]
你试一下 4.4.4版本，应该已经修复了。

**Comment by gaochongid** [comment]
4.4.4版本在IE10下还有同样的问题。
![5f738f57-7473-44d9-be14-42146afbb0f6](https://cloud.githubusercontent.com/assets/4160727/15810259/48812812-2bcf-11e6-9c18-3292d5e72514.png)

调试的时候，buffer对象已构造，但是没有fill方法。
![de1d8796-6b85-4544-b487-7e92d4b033fd](https://cloud.githubusercontent.com/assets/4160727/15810298/79c6e51a-2bcf-11e6-9057-397eb72b258d.png)

**Comment by rockuw** [comment]
你用的是哪个方法？你的代码是怎样写的？

**Comment by gaochongid** [comment]
<script src="https://www.promisejs.org/polyfills/promise-6.1.0.js"></script>

<script type="text/javascript" src="http://gosspublic.alicdn.com/aliyun-oss-sdk.min.js"></script>

client = new OSS.Wrapper({
    region: data.region,
    accessKeyId: data.access_key_id,
    accessKeySecret: data.access_key_secret,
    stsToken: data.security_token,
    bucket: data.bucket,
    secure: true
});

**Comment by rockuw** [comment]
`new OSS.Wrapper`这句就报错了？

**Comment by gaochongid** [comment]
恩。没有得到OSS对象。
这是oss-in-browser运行的结果：
![4b948c3b-7fd0-4311-b849-07dc50a7a859](https://cloud.githubusercontent.com/assets/4160727/15811065/5c4f80ac-2bd7-11e6-985f-a5b4fdba3206.png)

**Comment by rockuw** [comment]
奇怪，我在win7下的IE10测试是没有问题的：

![image](https://cloud.githubusercontent.com/assets/1209779/15811082/9c4a6a32-2bd7-11e6-9a56-af2ae584ba73.png)

**Comment by gaochongid** [comment]
我再找个环境试一下。

**Comment by gaochongid** [comment]
我也安装了一下win7，在IE10上确实没有问题。
之前报错的环境是win8.1，IE11文档模式为IE10的情况下。
麻烦了，谢谢。

**Comment by rockuw** [comment]
不客气，谢谢反馈，IE11我再去测试一下。

**Comment by gaochongid** [comment]
恩，我刚测了一下，没发现问题。

**Comment by rockuw** [comment]
“在IE11下使用兼容模式”的问题先不管了。
