### ISSUE TITLE
https的接口，会跳转到80端口，ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by zhuyuanwen** [rockuw/oss-in-browser#9]
![image](https://user-images.githubusercontent.com/12319327/30528174-0755e6e2-9c63-11e7-8306-b4ea3ba1d95a.png)

**Comment by zhuyuanwen** [comment]
@rockuw

**Comment by rockuw** [comment]
如果你的站点是https，那么你需要使用OSS的https endpoint：构造OSS client时增加`secure: true`参数。

**Comment by zhuyuanwen** [comment]
![image](https://user-images.githubusercontent.com/12319327/30530699-98c67d4a-9c7b-11e7-8bfd-5387599a04bb.png)

@rockuw 这样子是么？好像成功了，谢谢！
